spring:
  datasource:
    # URL de conexão com o banco de dados H2 em memória
    url: jdbc:h2:mem:sdw2023
    # Nome de usuário para autenticação no banco de dados
    username: sdw2023
    # Senha do banco de dados (vazia, já que H2 permite conexão sem senha)
    password:

  jpa:
    # Exibe as consultas SQL no console durante a execução
    show-sql: true
    # Não mantém a sessão aberta após a visualização
    open-in-view: false
    # Configurações do Hibernate para o gerenciamento do esquema do banco de dados
    hibernate:
      # A estratégia de geração do esquema do banco de dados
      ddl-auto: create # outras opções: validate | update | create | create-drop
    properties:
      hibernate:
        # Formata as consultas SQL exibidas
        format_sql: true

  h2:
    console:
      # Habilita o console H2 para acesso via navegador
      enabled: true
      # Caminho de acesso ao console H2
      path: /h2-console
      settings:
        # Configurações adicionais para o console H2
        trace: false
        # Permite conexões de outros hosts (desativado por padrão)
        web-allow-others: false
